### ISSUE TITLE
能不能修正下 easyhttp/src/Http 的注解

### ISSUE THREAD

**Issue by xhwsd** [yzh52521/easyhttp#3]
能不能修正下 easyhttp/src/Http 的注解， 如 [34行](https://github.com/yzh52521/easyhttp/blob/a74fa5a1d4f701bd20e581b0731e885aac3daf9f/src/Http.php#L34) 返回值

**Comment by yzh52521** [comment]
没明白 注解哪里不对

**Comment by yzh52521** [comment]
已修复
