### ISSUE TITLE
请问异步访问网络时，必须用wait才能启动吗？

### ISSUE THREAD

**Issue by leamus** [yzh52521/easyhttp#5]
我在workerman中使用这个库来作为客户端访问网络，但我想异步访问网络不阻塞，经测试只能使用wait后数据才能发送，但wait之后就阻塞了进程，请问有没有不阻塞的方法呢？谢谢~

**Comment by yzh52521** [comment]
在 fpm 下是不需要 wait
workerman 中 还是建议用 workerma的  [workerman/http-client] (https://www.workerman.net/doc/workerman/components/workerman-http-client.html#workerman%2Fhttp-client)
的组件

**Comment by leamus** [comment]
好的，谢谢~~
